# Generated by Django 5.2.13 on 2026-05-03 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_school_customuser_is_project_admin_and_more'),
        ('communications', '0002_chatmessage_attachment_chatmessage_attachment_mime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='notificationreplacementitem',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_items', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='notificationstatus',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_statuses', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_notifications', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='ticketparticipant',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_participants', to='accounts.school'),
        ),
    ]
