# Generated by Django 5.2.11 on 2026-05-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_chatmessage_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_attachments/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='attachment_mime',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
