# Generated by Django 5.0.6 on 2025-06-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacements', '0003_classschedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='shift',
            field=models.IntegerField(choices=[(1, '1 смена'), (2, '2 смена')], default=1, verbose_name='Смена'),
        ),
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together={('class_group', 'lesson_number', 'shift')},
        ),
    ]
