# Generated by Django 5.2.11 on 2026-04-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Роль «Администратор» (полный доступ)'),
        ),
    ]
