# Generated by Django 5.2.11 on 2026-04-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_system_account',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Системный аккаунт (служебный)'),
        ),
    ]
