# Generated by Django 5.2.13 on 2026-05-03 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_is_system_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('street', models.CharField(blank=True, default='', max_length=180)),
                ('house', models.CharField(blank=True, default='', max_length=32)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=64)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts_school',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_project_admin',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Роль «Администратор проекта»'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_support_system',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Система поддержки (служебный)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Роль «Администратор школы»'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.school'),
        ),
    ]
